### ISSUE TITLE
this

### ISSUE THREAD

**Issue by arceuss** [BlobEmoji/pokeblob-js#41]
Uncaught Promise Error:  { Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by OGNova** [comment]
This is not an issue with the code, and as such, will be closed.

This is an issue with your internet going down and the bot losing connection to Discord. I highly recommend you do not attempt to host the bot yourself, and wait until a version is made public in the coming weeks.
